"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Core } from '@ag.ds-next/react/core';
import { theme } from '@ag.ds-next/react/ag-branding';
import { LinkComponent } from './LinkComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Core theme={theme} linkComponent={LinkComponent}>
   
      <body >{children}</body>
    
    </Core>
  )
}
